# Generated by Django 4.2 on 2023-06-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FC_football_Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('match_Date', models.DateField()),
                ('match_Time', models.TimeField()),
                ('match_player', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jangseong_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('match_Date', models.DateField()),
                ('match_Time', models.TimeField()),
                ('match_player', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NC_skyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('match_Date', models.DateField()),
                ('match_Time', models.TimeField()),
                ('match_player', models.IntegerField(default=0)),
            ],
        ),
    ]
