# Generated by Django 4.2 on 2023-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_fc_football_center_id_alter_jangseong_field_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nc_skyfield',
            name='match_level1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nc_skyfield',
            name='match_level2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nc_skyfield',
            name='match_level3',
            field=models.IntegerField(default=0),
        ),
    ]
