# Generated by Django 4.2 on 2023-05-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_alter_user_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(default='', max_length=20),
        ),
    ]
