# Generated by Django 4.2 on 2023-05-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
